### ISSUE TITLE
Non-Github mirrors

### ISSUE THREAD

**Issue by JayBrown** [jmdugan/blocklists#79]
Would it be possible to create (and auto-update) non-GitHub mirrors?

As it stands, [**GasMask**](https://github.com/2ndalpha/gasmask) on macOS is not able to read URLs that lead to the raw files on GitHub.

Example: SteveBlack also mirrors [**his hosts files**](https://github.com/StevenBlack/hosts) on non-GitHub sites.

**Comment by timvisee** [comment]
You could mirror it on GitLab. Simply create a repository, and configure a pull mirror in it's settings. Or is this not what you're looking for?

**Comment by JayBrown** [comment]
I tried doing that, but it's the same error: "Can't download the hosts file. It contains unknown content".

URLs tried:
https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
https://gitlab.com/JayBrown/blocklists-mirror/-/raw/master/corporations/facebook/all

Those git platforms are doing something weird, even though it's supposed to be a raw link. So a true external mirror would be needed instead.

**Comment by jmdugan** [comment]
source for gasmask is available from github

it's throwing and error because it thinks the content-type header is wrong.  (function "addUnknownContentTypeError")

curl -v -I "https://gitlab.com/JayBrown/blocklists-mirror/-/raw/master/corporations/facebook/all" | less
shows the headers, including
content-type: text/plain; charset=utf-8

in gasmask, see HostsDownloader.m lines 185, 108, 29, etc. to follow the process

on quick inspection, it looks like it should work, the header returned from that URL begins with the text "text/plain"

don't have time (or experience with obj-c) to debug it now; it looks like a bug in gasmask?
